def get_generate_revenue(sales):
  # initializes counters
  revenue = 0
  total_sales = 0

  # validates that there are sales
  if not sales or len(sales) == 0:
    print('No se ha generado ingresos porque no existen ventas.')
  else:
    # runs through the matrix, each position is a sale.
    for sale in sales:
      count_sale = sale[3] # the index 3 of the array corresponds to the number of items sold of that product
      price_product = sale[2] # index 2 corresponds to the price of the product

      total_gain_sales = count_sale * price_product # calculate the total revenue generated from that sale

      total_sales += count_sale # increases the total sales counter
      revenue += total_gain_sales # increases the total profit counter with the profit generated by the current sale
    
    # generates the report to the user
    print(f'Los ingresos generados por {total_sales} ventas es de $ {revenue}')
